api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
#    formats:
#        json:
#            mime_types: ['application/json']
    eager_loading:
        enabled: true
    collection:
        pagination:
#            enabled: false
            page_parameter_name: _page
#            client_enabled: true
#            enabled_parameter_name: pagination
            items_per_page: 4
